[project]
name = "gpt4-tokenizer"
version = "0.1.0"
description = "GPT-4 tokenizer from scratch"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "regex>=2025.9.18",
    "tiktoken>=0.11.0",
]
